/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UcBadge {
        /**
          * Type of the badge.
         */
        "type": "info" | "warning" | "success" | "error";
    }
}
declare global {
    interface HTMLUcBadgeElement extends Components.UcBadge, HTMLStencilElement {
    }
    var HTMLUcBadgeElement: {
        prototype: HTMLUcBadgeElement;
        new (): HTMLUcBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "uc-badge": HTMLUcBadgeElement;
    }
}
declare namespace LocalJSX {
    interface UcBadge {
        /**
          * Type of the badge.
         */
        "type"?: "info" | "warning" | "success" | "error";
    }
    interface IntrinsicElements {
        "uc-badge": UcBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uc-badge": LocalJSX.UcBadge & JSXBase.HTMLAttributes<HTMLUcBadgeElement>;
        }
    }
}
