import {Config} from "@stencil/core"
import {
  vanillaExtractRollupPlugin,
  vanillaExtractStencilPlugin,
} from "stencil-vanilla-extract-plugin"

import {reactOutputTarget as react} from "@stencil/react-output-target"

export const config: Config = {
  globalScript: "./src/global.ts",
  namespace: "universal-components",
  outputTargets: [
    react({
      componentCorePackage: "universal-components",
      customElementsDir: "dist/components",
      includeImportCustomElements: true,
      // This file gets generated by React wrapper function and contains definitions of all Wrapper components
      proxiesFile: "../react/src/components/stencil-generated/index.ts",
    }),
    {
      esmLoaderPath: "../loader",
      type: "dist",
    },
    {
      type: "dist-custom-elements",
    },
    {
      type: "docs-readme",
    },
    {
      serviceWorker: null,
      type: "www", // disable service workers
    },
  ],
  plugins: [vanillaExtractStencilPlugin()],
  rollupPlugins: {
    before: [vanillaExtractRollupPlugin()],
  },
}
